---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openconnect-deployment
  namespace: vpn
  labels:
    app: openconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openconnect
  template:
    metadata:
      labels:
        app: openconnect
    spec:
      containers:
      - name: openconnect
        image: markusmcnugen/openconnect
        ports:
        - containerPort: 4443
          protocol: TCP
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-service
  namespace: vpn
spec:
  ports:
  - name: https
    port: 4443
    targetPort: 4443
    protocol: TCP
  selector:
    app: openconnect
  type: LoadBalancer
