---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-deployment
  namespace: vpn
  labels:
    app: openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      containers:
      - name: openvpn
        image: openvpn-as:latest
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        - containerPort: 1194
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-service
  namespace: vpn
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: admin
    port: 9443
    targetPort: 9443
    protocol: TCP
  - name: openvpn
    port: 1194
    targetPort: 1194
    protocol: UDP
  selector:
    app: vpn

